name: Build

on:
  push:
  pull_request:

jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    env:
      LD_LIBRARY_PATH: /usr/local/lib
    steps:
      - name: Instlall tools
        run: |
          sudo apt install -y gauche wget make libgmp-dev autoconf automake
          sudo apt install -y re2c bison subversion git
      - name: Install Oniguruma
        run: |
          wget https://github.com/kkos/oniguruma/releases/download/v5.9.6/onig-5.9.6.tar.gz
          tar zvxf onig-5.9.6.tar.gz
          cd onig-5.9.6
          rm config.sub
          rm config.guess
          wget http://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.guess
          wget http://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.sub
          ./configure
          make
          sudo make install
      - name: Install the latest stable Mosh
        run: |
          wget https://github.com/higepon/mosh/releases/download/mosh-0.2.8-rc3/mosh-0.2.8-rc3.tar.gz
          tar zvxf mosh-0.2.8-rc3.tar.gz
          cd mosh-0.2.8-rc3
          ./configure
          make
          make test
          sudo make install
      - uses: actions/checkout@v3
      - name: Build and test the latest changes.
        run: |
          cd ${{ github.workspace }}
          ./gen-git-build.sh
          ./configure
          make
          make test
          sudo make install

  build-macos:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-12]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    env:
      CPATH: /opt/homebrew/include
      LIBLARY_PATH: /opt/homebrew/lib
    steps:
      - name: Instlall tools
        run: |
          brew install gmp oniguruma automake
      - name: Install the latest stable Mosh
        run: |
          wget https://github.com/higepon/mosh/releases/download/mosh-0.2.8-rc3/mosh-0.2.8-rc3.tar.gz
          tar zvxf mosh-0.2.8-rc3.tar.gz
          cd mosh-0.2.8-rc3
          ./configure
          make
          make test
          sudo make install
      - uses: actions/checkout@v3
      - name: Build and test the latest changes.
        run: |
          cd ${{ github.workspace }}
          ./gen-git-build.sh
          ./configure
          make
          make test
          sudo make install
